import type { Metadata } from "next";
import { Funnel_Display } from "next/font/google";
import "./globals.css";
import { GlobalStoreProvider } from "@/context/GlobalStore";

const funnelDisplay = Funnel_Display({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${funnelDisplay.className}`}>
                <GlobalStoreProvider>{children}</GlobalStoreProvider>
            </body>
        </html>
    );
}
