name: CI - Tests & Coverage

on:
    workflow_dispatch:
        inputs:
            shards:
                description: "Select number of shards to split tests"
                required: true
                default: "1"
                type: choice
                options:
                    - "1"
                    - "2"
                    - "4"
                    - "8"
                    - "12"
                    - "15"
    pull_request:
        types:
            - opened

jobs:
    pre-processing:
        name: Generate Matrix & Prepare shards
        runs-on: ubuntu-latest
        outputs:
            shards: ${{ steps.set-shard-files.outputs.shards }}
        steps:
            # Checkout repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Setup Node.js and install dependencies
            - name: Setup Node.js & Install dependencies
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - run: yarn install --frozen-lockfile

            - name: Generate shard test files
              id: set-shard-files
              run: |
                  FILES=$(node scripts/distributeTests.mjs --shards ${{steps.set-shard-files.outputs.shards}})
                  echo "shards=$FILES" >> "$GITHUB_OUTPUT"

    test-shards: # runs tests in parallel shards
        name: Test Shards
        runs-on: ubuntu-latest
        needs: pre-processing
        strategy:
            fail-fast: false
            matrix:
                shard: ${{ fromJSON(needs.pre-processing.outputs.shards) }}
        steps:
            # Checkout repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Setup Node.js and install dependencies
            - name: Setup Node.js & Install dependencies
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: "yarn"
            - run: yarn install --frozen-lockfile

            # Run tests using sharding
            - name: Run tests
              env:
                  NODE_OPTIONS: "--max_old_space_size=8192"
              run: |
                  yarn test ${{ matrix.shard.files }} \
                    --silent --verbose \
                    --coverage \
                    --coverageReporters=json \
                    --passWithNoTests

              # Cache coverage artifact
            - name: Coverage
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-shard-${{ matrix.shard.index }}
                  path: coverage/
                  retention-days: 1

    merge-coverage: # merges coverage results from all shards
        needs: test-shards
        name: Merge Coverage
        runs-on: ubuntu-latest
        steps:
            # Setup Node.js and install dependencies
            - name: Setup Node.js & Install dependencies
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            # Download all coverage artifacts
            - name: Download coverage artifacts
              uses: actions/download-artifact@v4
              with:
                  path: coverage-reports/

            # Merge coverage reports from all shards
            - name: Merge coverage reports
              run: |
                  npm install -g nyc

                  # Create merge directory
                  mkdir -p merged-coverage

                  # Collect coverage-final.json files
                  find coverage-reports -name "coverage-final.json" -type f | while read -r file; do
                    parent_dir=$(basename "$(dirname "$file")")
                    mv "$file" "merged-coverage/${parent_dir}.json"
                  done

                  # Merge coverage using nyc
                  npx nyc merge merged-coverage merged-coverage.json
                  npx nyc report --reporter=html --reporter=text --reporter=lcov --temp-dir=merged-coverage

            # Upload final merged coverage report
            - name: Upload merged coverage
              uses: actions/upload-artifact@v4
              with:
                  name: merged-coverage
                  path: |
                      coverage/
                      merged-coverage.json
